name: Compress Files

on:
  workflow_dispatch:

jobs:
  compress:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Check branch (fail if main)
      run: |
        BRANCH=$(git branch --show-current)
        if [ "$BRANCH" = "main" ]; then
          echo "Cannot run this workflow on main branch."
          exit 1
        fi
        echo "ORIGINAL_BRANCH=$BRANCH" >> $GITHUB_ENV

    - name: Set vars
      run: |
        export TZ="Europe/Berlin"
        echo "NEW_BRANCH=$(date +%Y.%m.%d_%H-%M-%S)_compress" >> $GITHUB_ENV

    - name: Setup git
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git switch -c $NEW_BRANCH
        git push --set-upstream origin $NEW_BRANCH

    - name: Ensure zip is available
      run: sudo apt-get update && sudo apt-get install -y zip

    - name: Compress project folders
      run: |
        mkdir -p projects/.compressed
        for dir in projects/*; do
          if [ -d "$dir" ]; then
            folder_name=$(basename "$dir")
            if [ "$folder_name" = ".compressed" ]; then
              continue
            fi
            output_path=$(readlink -m "projects/.compressed/adts-${folder_name}.zip")
            rm -f "$output_path"
            (cd "$dir" && zip -r "$output_path" .)
          fi
        done

    - name: Commit Changes
      run: |
        git add projects/.compressed/
        git commit -m "Compress Project Files" || echo "No changes to commit"
        git push

    - name: Create PR
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        base: ${{ env.ORIGINAL_BRANCH }}
        head: ${{ env.NEW_BRANCH }}
        title: "[AUTOMATED] Add compressed files"
        body: "This PR was generated automatically."
        assignees: ${{ github.triggering_actor }}
