name: Compress Files

on:
  workflow_dispatch:

jobs:
  compress:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install zip utility
      run: sudo apt-get install zip

    - name: Create zip directory if it doesn't exist
      run: mkdir -p zip

    - name: Compress project folders
      run: |
        for dir in projects/*; do
          if [ -d "$dir" ]; then
            folder_name=$(basename "$dir")
            zip -r "zip/project-files-${folder_name}.zip" "$dir"
          fi
        done
    - name: Commit Changes
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add zip/
        git commit -m "Compress Project Files (#5)" || true
        git push origin HEAD:main
