name: Compress Files

on:
  workflow_dispatch:

jobs:
  compress:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Setup git
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        TZ='Europe/Berlin
        BRANCH_NAME="$(date +%Y.%m.%d_%H-%M-%S)_$(git branch --show-current)_compress"
        git switch -c $BRANCH_NAME 
        git push --set-upstream origin $BRANCH_NAME

    - name: Install zip utility
      run: sudo apt-get install zip

    - name: Create zip directory if it doesn't exist
      run: mkdir -p zip

    - name: Compress project folders
      run: |
        for dir in projects/*; do
          folder_name=$(basename "$dir")
          if [ -d "$dir" ] && [ "$folder_name" != ".zip" ]; then
            zip -r "projects/.compressed/project-files-${folder_name}.zip" "$dir"
          fi
        done

    - name: Commit Changes
      run: |
        git add projects/.compressed/
        git commit -m "Compress Project Files" || true
        git push
