name: Compress Files

on:
  workflow_dispatch:

jobs:
  compress:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set vars
      run: |
        export TZ="Europe/Berlin"
        echo "ORIGINAL_BRANCH=$(git branch --show-current)" >> $GITHUB_ENV
        echo "NEW_BRANCH=$(date +%Y.%m.%d_%H-%M-%S)_$(git branch --show-current)_compress" >> $GITHUB_ENV
    - name: Setup git
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git switch -c $NEW_BRANCH 
        git push --set-upstream origin $NEW_BRANCH
    - name: Install zip utility
      run: sudo apt-get install zip

    - name: Compress project folders
      run: |
        for dir in projects/*; do
          if [ -d "$dir" ]; then
            # get just name of folder from path
            folder_name=$(basename "$dir")
            # get absolute path of target location for zip file
            output_path=$(readlink -m "projects/.compressed/adts-${folder_name}.zip")
            # remove existing zip file to avoid keeping deleted files
            rm -f "$output_path"
            # cd to avoid unnecessary nesting of files
            cd "$dir"
            zip -r "$output_path" .
            # cd back to previous dir 
            cd -
          fi
        done
    - name: Commit Changes
      run: |
        git add projects/.compressed/
        git commit -m "Compress Project Files" || true
        git push
    
    - name: Create PR
      run: |
        echo $NEW_BRANCH
        gh pr create --base $ORIGINAL_BRANCH --head $NEW_BRANCH --title "[AUTOMATED] Add compressed files" --body "" --assignee "${{ github.triggering_actor }}"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
