name: Copy Java Files To BlueJ Project

on:
  push:
    paths:
      - 'src/main/java/**' # Trigger only when changes occur in src/main/java/

jobs:
  copy_files:
    runs-on: ubuntu-latest
    permissions: write-all
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Copy Java Files
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          mkdir -p projects/bluej/
          rm projects/bluej/*.java
          cp -r src/main/java/* projects/bluej/
          
          for file in projects/bluej/*.java; do
            
            first_line=$(head -n 1 "$file")
            
            if [[ $first_line == package* ]]; then
              sed -i '1d' "$file"
            fi
          done
          
          git add projects/bluej/
          git commit -m "Update BlueJ Project Files" || true
          git push
