name: Copy Java Files To BlueJ Project

on:
  push:
    paths:
      - 'src/main/java/**' # Trigger only when changes occur in src/main/java/

jobs:
  copy_files:
    runs-on: ubuntu-latest
    permissions: write-all
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Copy Java Files
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          
          mkdir -p projects/bluej/
          cp -r src/main/java/* projects/bluej/
          
          git add projects/bluej/
          git commit -m "Update BlueJ Project Files" || true # Ignore error if no changes
          git push
