name: Create Projects

on:
  workflow_dispatch:

jobs:
  copy_files:
    runs-on: ubuntu-latest
    permissions: write-all
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check branch (fail if main)
        run: |
          BRANCH=$(git branch --show-current)
          if [ "$BRANCH" = "main" ]; then
            echo "Cannot run this workflow on main branch."
            exit 1
          fi
          echo "ORIGINAL_BRANCH=$BRANCH" >> $GITHUB_ENV

      - name: Set vars
        run: |
          export TZ="Europe/Berlin"
          echo "NEW_BRANCH=$(date +%Y.%m.%d_%H-%M-%S)_projects" >> $GITHUB_ENV

      - name: Setup git and create branch
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git switch -c $NEW_BRANCH
          git push --set-upstream origin $NEW_BRANCH

      - name: Create BlueJ Project
        run: |
          mkdir -p projects/bluej/
          rm -f projects/bluej/*.java
          
          cp -r src/main/java/*.java projects/bluej/
          
          for file in projects/bluej/*.java; do
            first_line=$(head -n 1 "$file")
            if [[ $first_line == package* ]]; then
              sed -i '1d' "$file"
            fi
          done

      - name: Commit Changes
        id: commit
        run: |
          git add projects/
          if git diff --cached --quiet; then
            echo "no_changes=true" >> $GITHUB_ENV
          else
            git commit -m "Update Project Files"
            git push
            echo "no_changes=false" >> $GITHUB_ENV
          fi

      - name: Create PR
        if: env.no_changes == 'false'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ${{ env.ORIGINAL_BRANCH }}
          head: ${{ env.NEW_BRANCH }}
          title: "[AUTOMATED] Update Project Files"
          body: "This PR was generated automatically."
          assignees: ${{ github.triggering_actor }}
